export const JOB_CATEGORIES = [
  "Cleaning",
  "Office Cleaning",
  "Deep Cleaning",
  "Housekeeping",
  "Handyman",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Painter & Decorator",
  "Gardening",
  "Landscaping",
  "Window Cleaning",
  "Delivery Driver",
  "Courier",
  "Parcel Sorting",
  "Warehouse Operative",
  "Picker / Packer",
  "Forklift Driver",
  "Stock Replenishment",
  "Security Guard (SIA)",
  "Event Security",
  "Door Supervisor",
  "CCTV Operator",
  "Retail Assistant",
  "Shop Worker",
  "Cashier",
  "Sales Assistant",
  "Hospitality Staff",
  "Waiter / Waitress",
  "Kitchen Assistant",
  "Chef",
  "Bar Staff",
  "Care Assistant",
  "Support Worker",
  "Childcare / Babysitting",
  "Tutor",
  "Teaching Assistant",
  "IT Support",
  "Admin Assistant",
  "Receptionist",
  "Data Entry",
  "Customer Service",
  "Moving Help",
  "Removal Services",
  "Driver",
  "General Labour",
  "Construction Worker",
  "Site Worker",
  "Odd Jobs",
  "Maintenance",
  "Cleaning Supervisor",
  "Warehouse Supervisor"
];

